const movieActionTypes = {
  TOP_RATED_MOVIES_LOADED: "TOP_RATED_MOVIES_LOADED",
  TOP_RATED_MOVIES_LOADING_FAIL: "TOP_RATED_MOVIES_LOADING_FAIL",
  MOVIE_DETAILS_LOADED: "MOVIE_DETAILS_LOADED",
  MOVIE_DETAILS_LOADING_FAIL: "MOVIE_DETAILS_LOADING_FAIL",
  MOVIE_VIDEOS_LOADED: "MOVIE_VIDEOS_LOADED",
  MOVIE_VIDEOS_LOADING_FAIL: "MOVIE_VIDEOS_LOADING_FAIL",
  MOVIES_BY_TERM_LOADED: "MOVIES_BY_TERM_LOADED",
  MOVIES_BY_TERM_LOADING_FAIL: "MOVIES_BY_TERM_LOADING_FAIL",
  MOVIES_BY_TERM_IN_PROGRESS: "MOVIES_BY_TERM_IN_PROGRESS",
  SIMILAR_MOVIE_LOADED: "SIMILAR_MOVIE_LOADED",
  SIMILAR_MOVIE_LOADING_FAIL : "SIMILAR_MOVIE_LOADING_FAIL",
};

export default movieActionTypes;
