const tvShowActionTypes = {
  TOP_RATED_TV_SHOWS_LOADED: "TOP_RATED_TV_SHOWS_LOADED",
  TOP_RATED_TV_SHOWS_LOADING_FAIL: "TOP_RATED_TV_SHOWS_LOADING_FAIL",
  TV_SHOW_DETAILS_LOADED: "TV_SHOW_DETAILS_LOADED",
  TV_SHOW_DETAILS_LOADING_FAIL: "TV_SHOW_DETAILS_LOADING_FAIL",
  TV_SHOW_VIDEOS_LOADED: "TV_SHOW_VIDEOS_LOADED",
  TV_SHOW_VIDEOS_LOADING_FAIL: "TV_SHOW_VIDEOS_LOADING_FAIL",
  TV_SHOWS_BY_TERM_LOADED: "TV_SHOW_BY_TERM_LOADED",
  TV_SHOWS_BY_TERM_LOADING_FAIL: "TV_SHOW_BY_TERM_LOADING_FAIL",
  TV_SHOWS_BY_TERM_IN_PROGRESS: "TV_SHOWS_BY_TERM_IN_PROGRESS",
  SIMILAR_TV_SHOWS_LOADED: "SIMILAR_TV_SHOWS_LOADED",
  SIMILAR_TV_SHOWS_LOADING_FAIL : "SIMILAR_TV_SHOWS_LOADING_FAIL",
};

export default tvShowActionTypes;
